### PR TITLE
Juniper interfaces list

### PR DESCRIPTION
**Pull request by emmurd**
Reviewed-by: Félix Bouliane <fbouliane@internap.com>

### CODE REVIEW

**Comment by lindycoder** [comment]
You are missing some test cases here:

In the <members> of an interface, you can have
- A range (700-800) in which the vlan 705 would exist
- A name "VLAN705" which references the vlan by its name if i remember correcly, and you can have a custom name like 'blue' and have <members>blue<members>

**Comment by emmurd** [comment]
Closing to complete Martin's comment

**Comment by emmurd** [comment]
Range and aliases support integrated. Please review

**Comment by lindycoder** [comment]
:+1:

**Pull request merged**
