### PR TITLE
Fixed api_docs

### PR DESCRIPTION
**Pull request by lindycoder**
Pushing the fixtures in the package will have it deploy to the docs site
Also added the lock-provider to the info api

### CODE REVIEW

**Comment by idjaw** [comment]
:+1:

**Comment by godp1301** [comment]
Should the optional parameter of netman_api included in the PR be in a separate commit as it doesn't have to do with fixing the documentation?

**Comment by lindycoder** [comment]
Well it was actually the value i was delivering and the fixing of api is the side effet, i could split it into 2 PR... do i need to take the time to do that?

**Comment by mat128** [comment]
Why do you need the lock provider in the /info endpoint?

**Comment by lindycoder** [comment]
1 - it is a information configurable by the command line, which might be useful when investigating a running instance
2 - It will let me use it in tests in some other system that shares the api layer ;)

**Pull request merged**
