### PR TITLE
GetVersionsTest now inherits from ComplianceTestCase

### PR DESCRIPTION
**Pull request by fbouliane**
Add documentation to prevent this error to happen again.

### CODE REVIEW

**Comment by JoProvost** [comment]
Can you provide more context on why this matters?

**Comment by fbouliane** [comment]
The configured test case depends on another mecanism for do all the alternative switches. The complianceTestCase implements this mecanism.
Configuredtestcase will run only juniper
ComplianceTestCase will run all switches.

**Comment by lindycoder** [comment]
👍

**Comment by godp1301** [comment]
👍

**Pull request merged**
